image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:

 - java -jar ./artifacts/aqa-shop.jar -port=8080 -P:profile=test &

build_script:
 - chmod +x gradlew
 - ./gradlew test --info -D Selenide.headless=true
